services:
  wtb-postgres:
    image: postgres:14
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./postgres_db_init.sql:/docker-entrypoint-initdb.d/postgres_db_init.sql
volumes:
  postgres-db: